### ISSUE TITLE
Cannot run in `docker compose`

### ISSUE THREAD

**Issue by sarumont** [AngellusMortis/sxm-docker#5]
Since no username or password is passed in via CLI arguments to `sxm-player`, they are retrieved from `stdin`. This is not possible when running via `docker compose` (nor is it ideal when running in plain `docker`).

**Comment by AngellusMortis** [comment]
https://docs.docker.com/compose/environment-variables/set-environment-variables/

**Comment by sarumont** [comment]
https://sxm-player.readthedocs.io/en/latest/usage.html#sxm-parameters
